source 'https://supermarket.chef.io'

metadata
cookbook 'php', '~> 2.2.1'
cookbook 'apache2', '~> 3.2.2'
cookbook 'selinux', '= 0.5.0'
cookbook 'mysql', '~> 8.2.0'
cookbook 'yum-mysql-community', '~> 2.0.3'
cookbook 'vim', '~> 2.0.2'
